# Generated by Django 2.2.7 on 2019-11-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Nombre de la Persona', max_length=200)),
                ('field_last_name', models.CharField(help_text='Apellido de la Persona', max_length=200)),
                ('field_password', models.CharField(help_text='Contraseña', max_length=200)),
                ('field_email', models.EmailField(blank=True, max_length=254)),
                ('field_age', models.IntegerField(default=18, help_text='edad de la Persona')),
                ('field_phone', models.CharField(help_text='Numero de telefono', max_length=200)),
            ],
            options={
                'ordering': ['field_last_name', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_context', models.TextField(help_text='Contenido de la pregunta')),
                ('field_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Persona')),
            ],
        ),
    ]
