# Generated by Django 2.2.6 on 2019-11-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='field_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='persona',
            name='field_last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='field_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='field_password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='field_phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='field_context',
            field=models.TextField(),
        ),
    ]
