# Generated by Django 2.2.6 on 2019-11-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20191117_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='field_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
